### PR TITLE
Facets for all

### PR DESCRIPTION
**Pull request by voidshard**
@justinfx 
First crack at adding Facets to Collections, Resources & Links

It seems to be that there's no good reason not to allow facets on more things, and possibly some good reasons to if it encourages users to narrow down their search space to make queries lighter .. especially now that collections can have parents / children which are themselves collections. 

It does represent a breaking client change, albeit a minor one as it simply requires a ', nil' to be added to the end of create funcs. Worth at least a minor version bump I'd think .. possibly major.

### CODE REVIEW

**Comment by justinfx** [comment]
Breaking the API is a call you will have to make, since you tagged it as 1.0 already. Maybe you can come up with a different way to introduce the extra arguments, such as extra function variants (`NewCollectionVariant()`), or some form of variadic options `...`. Or you can just break the API if not that many users have started committing to the API :-)

**Comment by voidshard** [comment]
Well .. I don't know of too many ;). I could simply add the facets on, but not update the Create calls .. that way people would simply have to do 
```
foo := bar.AddResource(x, y, z)
foo.setFacets(map[string]string{x: y})
``` 
The only irritation is that then the CreateVersion and CreateItem calls are a bit different .. then again .. that doesn't really matter per se. And I guess it does mean that people's code doesn't need a whole lot of 'nil' values being passed into Create calls if they're not using the extra facets anyhow.

Hm .. I like that! Ok, I'll add facets for all, but not change the Create functions - instead you'll simply have to call Create then SetFacets on the returned struct .. Yay for consistency!

**Comment by voidshard** [comment]
Ok, another idea / variant: changed Create calls to use '...map[string]string' .. all previous code should work as per normal. This simply adds the ability to pass in facets on creation. Technically it allows passing in multiple maps, which I then amalgamate into the final Facet map .. but that doesn't seem too bad as I imagine this could be useful for setting default facets on the create calls via some kind of wrapper ..

**Comment by justinfx** [comment]
Using the variadic approach does mean that you  commit the function to only being able to accept facets as the creation option, as opposed to other potential options down the line. Are facets very special in that they should be the only option you would pass?

**Comment by voidshard** [comment]
True .. we could use either the Opts style with a
type CreateOption func (someInterface) 
... given that I use that already in the client, I'm not sure why I didn't use that again and went for ...map[x]x .. I must be more tired that I suspect.

**Comment by voidshard** [comment]
Updated with CreateOption  means we should be able to update with more Opts later. Also, I've left the interfaces the CreateOption func uses internal .. so we can add more funcs to that later to help with more opts :)

**Pull request merged**
