### PR TITLE
Redesign client search

### PR DESCRIPTION
**Pull request by voidshard**
Changing the search to use options style. Means less functions are offered in the API with just as much flexibility. 

It kind of requires a more intimate knowledge of the object's fields .. but it is a lot nicer I think. 

I've fixed all the Go examples & readme to use this style and it seems to work as previously.

### CODE REVIEW

**Comment by voidshard** [comment]
This means the client is pretty clean and I could remove the extra funcs that bugged me. I think after this we should be good to tag a version 1.

**Comment by justinfx** [comment]
I like this style instead of the chaining approach. It means you can have slices of search options that can be reused easily by just passing them to the search.

**Comment by voidshard** [comment]
Yeah it's nice! The only bit I think needs a tweak are the Limit and Offset options which at the moment are passed in like the other options .. even though they apply to the whole search.

I'm thinking either:
- Limit & offset should be set on the Search obj itself
```
search := Search(a, b, c)
search.SetLimit(10)
results, err := search.FindFoos()
```
- Limit & offset are 'QueryOptions' that are passed into the Find funcs so
```
results, err := Search(a, b, c).FindFoos(wysteria.Limit(10))
```
.. I like the second option more. Also if we're using Options style in the client we may as well be consistent!

**Comment by justinfx** [comment]
I think the second is better, as well. You can reuse a query, but with
different paging options for the actual retrieval.

**Comment by voidshard** [comment]
Ok! I've made the Limit / Offset options into opts style params too. They're passed into the 'Find' functions as one might expect

**Pull request merged**
